### ISSUE TITLE
fontawesome icons not working for me when using echo without -e

### ISSUE THREAD

**Issue by dhensen** [benjcalderon/dotfiles#4]
I took the volume part of your script and I had to use ` ` `echo -e` ` ` to get the FontAwesome sound icon to display properly. I wonder if you have an alias for echo in your {bash,zsh}rc file or that I am missing some other know-how.

https://github.com/benjcalderon/dotfiles/blob/master/bin/panel#L75

Maybe you know more about this?

**Comment by benjcalderon** [comment]
this dot files are outdated since I switched to GNOME. But I can tell you two things, I use zsh on the scripts and I have the standard zsh prezto configs. I noticed that zsh's echo works differently that bash, so that might be something to look for.

Thanks for opening the issue and I'll some day get to update these dotfiles (I should, I'm just too busy...)
